### ISSUE TITLE
python libs/wyproxy.py -p 8888 无法运行

### ISSUE THREAD

**Issue by YouYII** [fengxuangit/Fox-scan#12]
```
2016-12-08 13:20:42,091 [INFO] wyproxy is starting...
2016-12-08 13:20:42,091 [INFO] Listening: 0.0.0.0:8888 http
Traceback (most recent call last):
  File "libs/wyproxy.py", line 492, in <module>
    run(args)
  File "libs/wyproxy.py", line 471, in run
    wyproxy.run()
  File "libs/wyproxy.py", line 445, in run
    start_server(self.proxy_port, self.proxy_mode, self.unsave_data)
  File "libs/wyproxy.py", line 426, in start_server
    cadir="./ssl/",
TypeError: __init__() got an unexpected keyword argument 'cadir'
```

这个问题可能是mitmproxy 接口改了引起的 python 能指定依赖版本吗..

尝试修改 wyproxy.py的422行附近
> ops = options.Options(
>        app_port=port,
>        mode=mode,
>        cadir="./ssl/",
>    )
>    config = proxy.ProxyConfig(
>        ops
 >   )

这样修改修复了这个问题,但是还有下一个问题..
```
(venv) [root@localhost libs]# python wyproxy.py -p 8081
2016-12-08 13:32:10,097 [INFO] wyproxy is starting...
2016-12-08 13:32:10,098 [INFO] Listening: 0.0.0.0:8081 http
Traceback (most recent call last):
  File "wyproxy.py", line 495, in <module>
    run(args)
  File "wyproxy.py", line 474, in run
    wyproxy.run()
  File "wyproxy.py", line 448, in run
    start_server(self.proxy_port, self.proxy_mode, self.unsave_data)
  File "wyproxy.py", line 434, in start_server
    m = WYProxy(server, state, unsave_data)
  File "wyproxy.py", line 381, in __init__
    super(WYProxy, self).__init__(server, state)
TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by YouYII** [comment]
看起来是因为 m = WYProxy(server, state, unsave_data) 这里传入的参数少一个unsave_data好像没有被接受.

**Comment by YouYII** [comment]
找到问题了
380行
>super(WYProxy, self).__init__(server, state)
改为
>super(WYProxy, self).__init__(server, state,unsave_data)

然后下面又报错了

```
(venv) [root@localhost libs]# python wyproxy.py -p 8081
Namespace(daemon=False, mode='http', pidfile=None, port='8081', restart=False, stop=False, unsave=False)
2016-12-08 13:49:50,867 [INFO] wyproxy is starting...
2016-12-08 13:49:50,867 [INFO] Listening: 0.0.0.0:8081 http
False
Traceback (most recent call last):
  File "wyproxy.py", line 501, in <module>
    run(args)
  File "wyproxy.py", line 479, in run
    wyproxy.run()
  File "wyproxy.py", line 453, in run
    start_server(self.proxy_port, self.proxy_mode, self.unsave_data)
  File "wyproxy.py", line 438, in start_server
    unsave_data=unsave,
  File "wyproxy.py", line 381, in __init__
    super(WYProxy, self).__init__(server, state,unsave_data)
  File "/usr/local/Fox-scan/venv/lib/python2.7/site-packages/mitmproxy/flow/master.py", line 54, in __init__
    super(FlowMaster, self).__init__(options)
  File "/usr/local/Fox-scan/venv/lib/python2.7/site-packages/mitmproxy/controller.py", line 92, in __init__
    self.addons = addons.Addons(self)
  File "/usr/local/Fox-scan/venv/lib/python2.7/site-packages/mitmproxy/addons.py", line 14, in __init__
    master.options.changed.connect(self._options_update)
AttributeError: 'ProxyServer' object has no attribute 'changed'
```

**Comment by YouYII** [comment]
从入门到放弃 ..

**Comment by fengxuangit** [comment]
您好，  我经过测试 没有复现你的问题 一切都是正常的。 是不是你没有安装相应的库导致的？如果有疑问请发邮件给我下我的邮件地址 f4ngxuan520@gmail.com
