### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by rsj123** [fengxuangit/Fox-scan#6]
C:\Users\rsj\Downloads\Fox-scan-master>views.py
Traceback (most recent call last):
  File "C:\Users\rsj\Downloads\Fox-scan-master\views.py", line 10, in <module>
    from libs.action import SqlMapAction,Spider_Handle,Save_Success_Target
  File "C:\Users\rsj\Downloads\Fox-scan-master\libs\action.py", line 12, in <module>
    import ipdb
  File "build\bdist.win32\egg\ipdb\__init__.py", line 7, in <module>
  File "build\bdist.win32\egg\ipdb\__main__.py", line 31, in <module>
ImportError: No module named IPython.core.debugger

**Comment by fengxuangit** [comment]
hi 我已经修复这个BUG  没有引入ipdb了 请更新最新代码
